#!/bin/bash

# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

MANUFACTURER=matsunichi
DEVICE=griffin

source="$1"
local_tmpdir="/tmp"
device_tmpdir="/data/local/tmp"

. ./useful-functions.sh


OUTDIR=vendor/$MANUFACTURER/$DEVICE
OUTDIR_REL=../../../$OUTDIR
VENDOR_BLOBS=$OUTDIR_REL/device-vendor-blobs.mk


cat << EOF > $VENDOR_BLOBS
# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/$MANUFACTURER/$DEVICE/extract-files.sh - DO NOT EDIT

PRODUCT_COPY_FILES += \\
EOF

copy_files "$source" proprietary-files.txt $OUTDIR/proprietary $VENDOR_BLOBS || exit $?
copy_files "$source" prebuilt-files.txt $OUTDIR/prebuilt $VENDOR_BLOBS || exit $?
echo >> $VENDOR_BLOBS

copy_files "$source" other-files.txt prebuilt || exit $?


exit 0
